# -*- coding: utf-8 -*-
"""Counter Most Common.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qqssMhUqLk3rFGQ4y8f8EszJorTe2ZEC
"""

from collections import Counter

age = [17, 16, 12, 17, 27, 24, 86, 43, 43, 47, 33, 90, 65, 77, 24, 51, -1, 24, 900, 24]

value_counts = Counter(age)

value_counts

value_counts.most_common(1)

value_counts.most_common(3)

